### ISSUE TITLE
object shadows and reflections

### ISSUE THREAD

**Issue by OmarSayedMostafa** [almarklein/visvis#105]
Is there anyway to render the shadows of objects according to light position and if not where should i implement the part of shadow and reflection ?

**Comment by almarklein** [comment]
Visvis does not have builtin functionality for that. I am not sure how hard it would be to make it work (I have never done anything like that), but you'd probably need to work with the interbals of visvis a bit, and know your way around with OpenGL ...

**Comment by almarklein** [comment]
This won't ever be supported in Visvis.

Have a look at [PyGfx](https://github.com/pygfx/pygfx), where we did implement it recently, see e.g. [this example](https://pygfx.readthedocs.io/en/latest/_gallery/feature_demo/plot_light_shadow.html)
