### ISSUE TITLE
Images Off Center

### ISSUE THREAD

**Issue by AndrewHornstra** [almarklein/visvis#108]
I am getting the following issue with PyQt5:

<img width="559" alt="screenshot 2018-10-22 12 03 54" src="https://user-images.githubusercontent.com/22163568/47314837-d4094c00-d610-11e8-9ab0-7ad40dccaaa6.png">

For various reasons, I am only able to use PyQt5 and no other supported backends.

There are a few interesting things about this:

I am not getting this bug in any other PyQt5 apps in the same Python environment, which is why I am posting here.

The images are off center, but they can only be manipulated by interacting with the region of the UI where they are supposed to appear.

There are no other side effects from this. The image above was produced using the example code (with my own data) found here:

https://github.com/almarklein/visvis/wiki/example_volumeRenderStyles

But the issue appears when using that sample data as well.

I am using:
MacOS Mojave
Python 3.7
Visvis 1.11.1
Numpy 1.14.5
pyOpenGL 3.1.0
PyQt 5.11.3

However, this issue was also present on:
MacOS High Sierra
Python 3.6.x
The previous versions of Visvis, PyQt5, and pyOpenGL; I do not recall the exact versions.

If someone else had this problem and could direct me to a solution, I would appreciate it. I have not opened an issue before, so I do not know exactly what would be expected in terms of provided information. I can provide more information if needed.

**Comment by almarklein** [comment]
I suspect that this is related to a difference between logical and physical pixels, because of a high resolution display. This PR in another project seems to target the same issue: https://github.com/pyqtgraph/pyqtgraph/pull/516

I don't think that my old Mac that I have in the closet has a HDPI display, so it would be hard for me to try. If you want, you could try applying the fix mentioned above here: https://github.com/almarklein/visvis/blob/master/backends/qtcommon.py#L321 I think this is where the fix should be applied, but I am not sure if changes are needed in other places ...

**Comment by AndrewHornstra** [comment]
Thank you, the fix in the second link fixed the image alignment.

It did introduce other weird behaviors that do not affect what I am doing too much.

When using vv.subplot, I am only able to manipulate the images from using the bottom two images (using the example screenshot given above). I do not know if this is intentional. Additionally, vv.ColormapEditor seems to lose its functionality when I apply this fix. It could be that its own control zone(?) has shifted, but I have been unable to locate it.

The second problem persists with vv.plot, except the editor can (sometimes) be moved around the image. The first issue is resolved in vv.plot and the entire image can be used to manipulate it.

But this solves my issue, thank you.

**Comment by almarklein** [comment]
mmm, yeah, that special number `devicePixelRatio` must be taken into account in a few places ... but it's hard to say where beforehand. I should someday get my hands on a HDPI screen and look into this deeper ...

**Comment by almarklein** [comment]
That would be awesome!

**Comment by almarklein** [comment]
I've looked into this. It may now work. But I am not 100% sure - I hope to be able to have tested on an actual hidpi screen soon.
