### ISSUE TITLE
text color is always black

### ISSUE THREAD

**Issue by sleepywitti** [almarklein/visvis#113]
Hey,
first, thanks for this useful library, that I've used for that last few years for fast visualization.
Today I tried to adjust the axis color (`vv.gca().axis.axisColor`) and noticed that the text color remained black. This behavior is the same for all `vv.Text` objects. After some digging in the code, I found out that the color is given correctly to the FragmentShader in `text_freetype.py`. However multiplying the color with the texture (`gl_FragColor = color1 * gl_Color;`, line 123) does always result in a black color - at least for me. 
I could fix it by changing line 108 to `vec4 color1 = vec4(1.0, 1.0, 1.0, 0.0);`. It seems that the texture2D does only affect the alpha channel, but leaves the color untouched. Hence, the resulting color1 will always be `(0.0, 0.0, 0.0, alpha)`.

Although visvis is not in development anymore, it would be great to hotfix it - in case that this error can be reproduced. 

Best,
sleepywitti

**Comment by almarklein** [comment]
Thanks for reporting! This got burried in my email a bit. I'll certainly have a look, but I don't consider it too urgent. I'll have a look within a few weeks.

**Comment by almarklein** [comment]
This error was introduced when we fixed #113. We first had a luminance-alpha texture, so we could indeed multiply with the `gl_Color`. But now we have just an alpha texture, which means that its rgb values in the shader are zero instead of one. 

Fixed now: https://github.com/almarklein/visvis/commit/8b9042400319e81b88c783c8f19a19527b34c0b0

**Comment by sleepywitti** [comment]
Thanks for the feedback and the fix!

**Comment by almarklein** [comment]
and made a new releas.
