### ISSUE TITLE
RE: Backends for visvis w/ a small footprint for 32-bit arm devices?

### ISSUE THREAD

**Issue by silver2row** [almarklein/visvis#115]
Hello,

I have a small webcam and I am venturing in this realm of webcams and finding out how to save frames of my running webcam. 

...

I wanted to save these frames while the webcam was running. I see in imageio and visvis, respectively, it seems possible. Is this a regular thing in video processing?

I am asking b/c I cannot figure out how to get a backend on my board to promote webcam findings.

Seth

P.S. I am sure it is a board issue but if there is hope in this field of gathering frames while video is live, I would like to try.

**Comment by silver2row** [comment]
Hello,

Here is an update. I just used apt to install my "dependencies." I put that in parenthesis b/c I still get an odd error that I am not familiar with right now.

...

    Qt: XKEYBOARD extension not present on the X server.
    Traceback (most recent call last):
      File "/home/debian/.local/lib/python3.7/site-packages/visvis/backends/qtcommon.py", line 258, in 
    paintEvent
        self.figure.OnDraw()
      File "/home/debian/.local/lib/python3.7/site-packages/visvis/core/baseFigure.py", line 793, in 
     OnDraw
        self._Draw(DRAW_SHAPE)
      File "/home/debian/.local/lib/python3.7/site-packages/visvis/core/baseFigure.py", line 844, in _Draw
        gl.glDisable(gl.GL_LINE_SMOOTH)
      File "/home/debian/.local/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
        baseOperation = baseOperation,
    OpenGL.error.GLError: GLError(
            err = 1280,
            description = b'invalid enumerant',
            baseOperation = glDisable,
            cArguments = (GL_LINE_SMOOTH,)
    )
    Aborted

This is my error. Does this have to do w/ visvis or pyopengl or OpenGL in general?

Seth

P.S. I have recently been told that the board does not handle such processing so well but I want to stick w/ my findings.

**Comment by almarklein** [comment]
Are you interesting in rendering images, or only in reading from the webcam and sending/storing the frames somewhere? If only the latter, visvis is probably now what you should use.

You could try use `imagio` (or perhaps `imageio-ffmpeg`), or e.g. openvc.

**Comment by silver2row** [comment]
Hello,

I think you are right. The BBB or other boards are not for image or video processing that much. 

Seth

P.S. I will look to those other libraries.
