### ISSUE TITLE
Base64 AttributeError with Python 3.9

### ISSUE THREAD

**Issue by alexander318** [almarklein/visvis#116]
Hello!

After updating to Python 3.9, the library stopped working due to:
AttributeError: module 'base64' has no attribute 'decodestring'

The method seems to be employed only on rows (162 and 163) of constants.py, when two colormaps are created. Removing the rows (if the colormaps are not needed), or renaming the decodestring method to decodebytes seems to fix the issue. Tested on Python 3.9 and visvis==1.12.4.

-Alexander

**Comment by almarklein** [comment]
I'll try to fix this soon. Probably Monday.

**Comment by almarklein** [comment]
Fixed, and made a new release!

**Comment by almarklein** [comment]
Thanks again for the heads-up!
