### ISSUE TITLE
AVI Recorder returns only the first frame

### ISSUE THREAD

**Issue by chrismaliszewski** [almarklein/visvis#118]
Creating GIF works fine. But when I create AVI, the file has only the first frame.

The code:
```
# data is 4D array
t = vv.volshow2(data)
duration = 1/7
format = 'avi' #'gif'

aa = vv.gca()
ff = vv.gcf()
rec = vv.record(aa)
for ii in list(range(data.shape[0])) + list(reversed(list(range(data.shape[0])))):
   t.children[0].index = ii
   aa.Draw()
   ff.DrawNow()
rec.Stop()
rec.Export('d:/filename' + '.' + format, duration=duration)
```
Not sure what I am doing wrong.

**Comment by almarklein** [comment]
This is likely because videos are somewhat expected to have relatively large number of frames ... It is a common pitfall that videos of say 10 frames or so don't encode well.
