### ISSUE TITLE
How to cite this work

### ISSUE THREAD

**Issue by seanywang0408** [almarklein/visvis#119]
Hi, could you provide the citation bibtex of this work? I would like to cite it in my paper.

**Comment by seanywang0408** [comment]
I might temporarily cite this work as followed (not stardard). 

@misc{Almar2020,
  author = {Almar Klein},
  title = {visvis},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/almarklein/visvis}}
}

**Comment by seanywang0408** [comment]
Thank you for your great work again!

**Comment by almarklein** [comment]
Thanks for siting visvis! I just created a DOI for visvis via Zenodo. It's on front page in github. 

The link is also here: https://zenodo.org/badge/latestdoi/41725089 (it says its invalid at the moment, which I think is because it needs time to be registered at doi.org.
