### ISSUE TITLE
Scientific notation in axis

### ISSUE THREAD

**Issue by Axuni** [almarklein/visvis#121]
How to request the use of scientific notation in an axis?
I see that the notation is supported (axises.py) but I am not able to change the notation when using small values.
Thanks!

**Comment by almarklein** [comment]
Do you mean using e.g. `2.2e1` for 22.0?

**Comment by Axuni** [comment]
Exactly.

**Comment by almarklein** [comment]
Vispy tries to automatically select the notation, its not possible to tweak this.

**Comment by Axuni** [comment]
Ahh, pity.
Currently I have some plots with values within a range of 0 to 0.002.
As the ticks are still taking less than 9 characters, all I see in the axis is: 0.000 0.001 0.002
Any suggestions?
Otherwise, I will simply scale my data and add the scaling factor in the legend. I.e. m [1x10^3]

I would also like to thak you for this great tool for vsualization. It makes the processing of my data far easier.

**Comment by almarklein** [comment]
> Any suggestions?

Well, you could change the source code of your local version of visvis:

https://github.com/almarklein/visvis/blob/766ed97767b44a55a6ff72c742d7385e074d3d55/core/axises.py#L210-L244

> Otherwise, I will simply scale my data and add the scaling factor in the legend. I.e. m [1x10^3]

👍 

> I would also like to thak you for this great tool for visualization. It makes the processing of my data far easier.

❤️

**Comment by almarklein** [comment]
Reading this again, you can also simply specify the ticks explicitly: https://github.com/almarklein/visvis/wiki/cls_BaseAxis#xTicks
