### ISSUE TITLE
Line class (wobject) for which the color can be specified for each point.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [almarklein/visvis#22]
```
For each point, the value can be specified, similar as for the Mesh class.

If this is a scalar value, the point's color will be looked up in a colormap. 
If this is a 3D or 4D value, this specified RGB/RGBA directly. The mesh class 
also supports 2D values, which are then looked up in a texture. I'm not sure 
whether that would make sense for points in a 3D space though...

```

Original issue reported on code.google.com by `almar.klein@gmail.com` on 28 Mar 2011 at 10:24

**Comment by almarklein** [comment]
Visvis is in low maintenance mode. This feature won't be supported.

Have a look at [PyGfx](https://github.com/pygfx/pygfx), where it is supported, see e.g. [this example](https://pygfx.readthedocs.io/en/latest/_gallery/feature_demo/plot_line_segments.html)
