### ISSUE TITLE
Build documentation using sphynx/rst

### ISSUE THREAD

**Issue by GoogleCodeExporter** [almarklein/visvis#49]
```
Google code wiki is ok, but sphynx-generated docs are much nicer.

Not a show-stopper for version 1.7, but should definitely be done before 1.8.
```

Original issue reported on code.google.com by `almar.klein@gmail.com` on 16 Aug 2012 at 2:55

**Comment by almarklein** [comment]
mmm, now that we've moved to Github and have a new wiki, I am not sure how to update the docs. I bet I'll run into this soon ...

**Comment by almarklein** [comment]
I've updated the wikimaker script to produce docs for the Github wiki (markdown). This seemed an easier path, and produces pretty good results.
