### ISSUE TITLE
Only use OpenGl context when we can be sure it exists

### ISSUE THREAD

**Issue by GoogleCodeExporter** [almarklein/visvis#53]
Related to issue #48. The particular issue was fixed, but we should make sure 
that a simular thing is not present in other locations.

Also, we should document somewhere that visvis adopts a lazy approach for doing 
any opengl calls; they should only be called at draw-time and never at object 
creation.

Original issue reported on code.google.com by `almar.klein@gmail.com` on 27 Aug 2012 at 10:47

**Comment by almarklein** [comment]
I'm not even sure anymore what this was about. Closing.
