### ISSUE TITLE
Fix visvis compatibility with numpy 1.12.0 (TypeError: 'float' object cannot be interpreted as an integer)

### ISSUE THREAD

**Issue by jimwormold** [almarklein/visvis#89]
The following error (previously a warning in numpy 1.11.x) is shown when drawing:

```
File "c:\miniconda3\lib\site-packages\visvis\wobjects\polygonalModeling.py", line 402, in _GetFaces
    return faces.reshape((Nfaces, vpf))
TypeError: 'float' object cannot be interpreted as an integer
```

I assume an explicit cast from float to int is now required

Version info:

- Python: 3.5
- numpy: 1.12.0
- visvis: 1.9.3

**Comment by almarklein** [comment]
Thanks for reporting this!  Fixed in https://github.com/almarklein/visvis/commit/3bb7a72c29e7c16b9ce5ee01f414d24b29521fab

I will make a new release so that people can update and avoid this issue.
