### ISSUE TITLE
Display image at full resolution with no whitespace?

### ISSUE THREAD

**Issue by ekcheng** [almarklein/visvis#93]
Hello, 

I would like to display my webcam feed at full resolution with no whitespace around the image. So far I've been able to remove the axes, but the window still displays lots of white space around the image. Is there a simple command, like `matplotlib's` `bbox_inches = tight` or `pad_inches=0` that would do the trick?

Thanks.

**Comment by almarklein** [comment]
Something like this?
```
a = vv.gca()
a.SetLimits(margin=0.0001)
```

**Comment by ekcheng** [comment]
That did the trick. Thanks!
