### ISSUE TITLE
HiDPI support on Mac OS X and PyQt5/(4)

### ISSUE THREAD

**Issue by jonaslindemann** [almarklein/visvis#97]
Hi!

I have noticed that diagrams drawn on a MacBook with retina display is shown in the lower left corner of the window at a quarter of the size. This is apparently related to QGLWidget using actual device pixels. 

I am wondering if this is known or you need a helping hand fixing this if yes what is the best approach?

I did a quick hack by modifying Figure class in qtcommon.py:

    def __init__(self, parent, *args, **kwargs):
        
        # keep same documentation
        self.__doc__ = BaseFigure.__doc__
        self._widget = None
        self._widget_args = (parent, args, kwargs)
        if kwargs.get('create_widget', True):
            self.CreateWidget()

        # Determine pixel ratio - JL

        self.pixelRatio = int(self._widget.windowHandle().devicePixelRatio())            
        
        # call original init AFTER we created the widget
        BaseFigure.__init__(self)

and multiplying width and height with this constant in:

    def _GetPosition(self):
        """ Get the position of the widget. """
        if self._widget and not self._destroyed:
            tmp = self._widget.geometry()
            return tmp.left(), tmp.top(), tmp.width()*self.pixelRatio, tmp.height()*self.pixelRatio
        return 0, 0, 0, 0

I could try to help out and fix this, but I would like to know how it should be best implemented.

Thanks for a great library!

-- Jonas

**Comment by almarklein** [comment]
> I could try to help out and fix this, 

That would be awesome. I think that the code samples posted above are in the right direction. If you create a PR with a start, we can discuss further there. Thanks!

**Comment by jonaslindemann** [comment]
I will do that!

**Comment by lue** [comment]
Had the same issue and the provided hack fixed it. Thanks, @jonaslindemann !

**Comment by almarklein** [comment]
HiDPI support is now implemented. Please report any problems in a new issue.
