### ISSUE TITLE
Readme should specify the correct conda package

### ISSUE THREAD

**Issue by hmaarrfk** [almarklein/visvis#99]
Should be
```
conda install visvis
```
and not 
```
conda install vispy
```

Cool work :D

**Comment by hmaarrfk** [comment]
Ok, I totally didn't realize that you were also behind the vispy project.

You should probably promote the awesome work you are doing there!!!

**Comment by almarklein** [comment]
Thanks! That's a really silly typo :/

I'm no longer active for Vispy, but I agree that we could add a link to it in the readme.

**Comment by almarklein** [comment]
Done
